### ISSUE TITLE
no flush in producer interface

### ISSUE THREAD

**Issue by Ronnie-Lon** [aliyun/aliyun-log-java-producer#2]
missing flush that we've no idea is it ok now to make progress (write checkpoint and handle next batch) after send some data. the only choice seems to close the producer or hold all the ListenableFuture and wait

**Comment by brucewu-fly** [comment]
For the checkpoint case, we suggest you write the checkpoint when the data has been ack by the server in callback. please refer to [SampleProducerWithFuture.java#L98](https://github.com/aliyun/aliyun-log-producer-sample/blob/master/src/main/java/com/aliyun/openservices/aliyun/log/producer/sample/SampleProducerWithFuture.java#L98)
