### ISSUE TITLE
有线程泄漏的问题

### ISSUE THREAD

**Issue by Svti** [aliyun/aliyun-log-java-producer#4]
"aliyun-log-producer-234-timeout-thread-0" #1240 daemon prio=5 os_prio=0 tid=0x00007f6770002000 nid=0x73fee waiting on condition [0x00007f6728016000]
"aliyun-log-producer-234-io-thread-0" #1239 daemon prio=5 os_prio=0 tid=0x00007f69c8b3b800 nid=0x73fed waiting on condition [0x00007f6728117000]
"aliyun-log-producer-234-failure-batch-handler" #1238 daemon prio=5 os_prio=0 tid=0x00007f69c8b36800 nid=0x73fec waiting on condition [0x00007f6728218000]
"aliyun-log-producer-234-success-batch-handler" #1237 daemon prio=5 os_prio=0 tid=0x00007f69c8b35000 nid=0x73feb waiting on condition [0x00007f6728319000]
"aliyun-log-producer-234-mover" #1236 daemon prio=5 os_prio=0 tid=0x00007f69c8b22000 nid=0x73fea waiting on condition [0x00007f672841a000]
"aliyun-log-producer-233-timeout-thread-0" #1235 daemon prio=5 os_prio=0 tid=0x00007f6b9d4db000 nid=0x73fe9 waiting on condition [0x00007f672851b000]
"aliyun-log-producer-233-io-thread-0" #1234 daemon prio=5 os_prio=0 tid=0x00007f69c8b23000 nid=0x73fe8 waiting on condition [0x00007f672861c000]
"aliyun-log-producer-233-failure-batch-handler" #1233 daemon prio=5 os_prio=0 tid=0x00007f69c8b1e800 nid=0x73fe7 waiting on condition [0x00007f672871d000]
"aliyun-log-producer-233-success-batch-handler" #1232 daemon prio=5 os_prio=0 tid=0x00007f69c8b1d000 nid=0x73fe6 waiting on condition [0x00007f672881e000]
"aliyun-log-producer-233-mover" #1231 daemon prio=5 os_prio=0 tid=0x00007f69c8b1a000 nid=0x73fe5 waiting on condition [0x00007f672891f000]
"aliyun-log-producer-232-timeout-thread-0" #1230 daemon prio=5 os_prio=0 tid=0x00007f6b7c00c800 nid=0x73fe4 waiting on condition [0x00007f6728a20000]
"aliyun-log-producer-232-io-thread-0" #1229 daemon prio=5 os_prio=0 tid=0x00007f69c8b1b000 nid=0x73fe3 waiting on condition [0x00007f6728b21000]
"aliyun-log-producer-232-failure-batch-handler" #1228 daemon prio=5 os_prio=0 tid=0x00007f69c8b16800 nid=0x73fe2 waiting on condition [0x00007f6728c22000]
"aliyun-log-producer-232-success-batch-handler" #1227 daemon prio=5 os_prio=0 tid=0x00007f69c8b15000 nid=0x73fe1 waiting on condition [0x00007f6728d23000]
"aliyun-log-producer-232-mover" #1226 daemon prio=5 os_prio=0 tid=0x00007f69c8b11800 nid=0x73fe0 waiting on condition [0x00007f6728e24000]
"aliyun-log-producer-231-timeout-thread-0" #1225 daemon prio=5 os_prio=0 tid=0x00007f6b60012000 nid=0x73fde waiting on condition [0x00007f6728f25000]
"aliyun-log-producer-231-io-thread-0" #1224 daemon prio=5 os_prio=0 tid=0x00007f69c8b12800 nid=0x73fdd waiting on condition [0x00007f6729026000]
"aliyun-log-producer-231-failure-batch-handler" #1223 daemon prio=5 os_prio=0 tid=0x00007f69c8b0e000 nid=0x73fdc waiting on condition [0x00007f6729127000]
"aliyun-log-producer-231-success-batch-handler" #1222 daemon prio=5 os_prio=0 tid=0x00007f69c8b0c800 nid=0x73fdb waiting on condition [0x00007f6729228000]
"aliyun-log-producer-231-mover" #1221 daemon prio=5 os_prio=0 tid=0x00007f69c899c000 nid=0x73fda waiting on condition [0x00007f6729329000]
"aliyun-log-producer-230-timeout-thread-0" #1220 daemon prio=5 os_prio=0 tid=0x00007f6b54020800 nid=0x73fd9 waiting on condition [0x00007f672962a000]
"aliyun-log-producer-230-io-thread-0" #1219 daemon prio=5 os_prio=0 tid=0x00007f69c8b0a800 nid=0x73fd8 waiting on condition [0x00007f672972b000]
"aliyun-log-producer-230-failure-batch-handler" #1218 daemon prio=5 os_prio=0 tid=0x00007f69c89a9000 nid=0x73fd7 waiting on condition [0x00007f672982c000]
"aliyun-log-producer-230-success-batch-handler" #1217 daemon prio=5 os_prio=0 tid=0x00007f69c89a4800 nid=0x73fd6 waiting on condition [0x00007f672992d000]
"aliyun-log-producer-230-mover" #1216 daemon prio=5 os_prio=0 tid=0x00007f69c8993800 nid=0x73fd5 runnable [0x00007f6729a2e000]
"aliyun-log-producer-229-timeout-thread-0" #1215 daemon prio=5 os_prio=0 tid=0x00007f6b38011000 nid=0x73fd4 waiting on condition [0x00007f6729b2f000]
"aliyun-log-producer-229-io-thread-0" #1214 daemon prio=5 os_prio=0 tid=0x00007f69c89a5800 nid=0x73fd3 waiting on condition [0x00007f6729c30000]
"aliyun-log-producer-229-failure-batch-handler" #1213 daemon prio=5 os_prio=0 tid=0x00007f69c89a1800 nid=0x73fd2 waiting on condition [0x00007f6729d31000]
"aliyun-log-producer-229-success-batch-handler" #1212 daemon prio=5 os_prio=0 tid=0x00007f69c89a1000 nid=0x73fd1 waiting on condition [0x00007f6729e32000]
"aliyun-log-producer-229-mover" #1211 daemon prio=5 os_prio=0 tid=0x00007f69c899f800 nid=0x73fd0 runnable [0x00007f6729f33000]

一直往上涨

**Comment by brucewu-fly** [comment]
您好，这是您用法不当造成的
创建了太多的 producer 实例
请参考文档 - https://yq.aliyun.com/articles/682761
