### ISSUE TITLE
maven仓库下载不了0.3.1的jar，0.3.0的可以

### ISSUE THREAD

**Issue by wzgdxg** [aliyun/aliyun-log-java-producer#5]
maven仓库下载不了0.3.1的jar，0.3.0的可以

**Comment by wzgdxg** [comment]
仓库里没有构建好的jar。

`
aliyun-log-producer-0.3.1-javadoc.jar             2019-07-24 01:09    212306      
aliyun-log-producer-0.3.1-javadoc.jar.asc         2019-07-24 01:09       488     
aliyun-log-producer-0.3.1-javadoc.jar.md5         2019-07-24 01:09        32      
aliyun-log-producer-0.3.1-javadoc.jar.sha1        2019-07-24 01:09        40      
aliyun-log-producer-0.3.1-sources.jar             2019-07-24 01:09     32069      
aliyun-log-producer-0.3.1-sources.jar.asc         2019-07-24 01:09       488      
aliyun-log-producer-0.3.1-sources.jar.md5         2019-07-24 01:09        32      
aliyun-log-producer-0.3.1-sources.jar.sha1        2019-07-24 01:09        40      
aliyun-log-producer-0.3.1.jar.asc                 2019-07-24 01:09       488      
aliyun-log-producer-0.3.1.pom.asc                 2019-07-24 01:09       484     
`

**Comment by brucewu-fly** [comment]
好的，我们检查一下

**Comment by brucewu-fly** [comment]
0.3.2 可以下载，建议使用 0.3.2 版本
